EH:
  auto_email: 'NO'
  delete_on_send: 'YES'
  email_recipients: ['jamesdeanbarrett@gmail.com; jamesdeanbarrett@hotmail.com;']
KB:
  auto_email: 'YES'
  delete_on_send: 'YES'
  email_recipients: [ 'jamesdeanbarrett@gmail.com; jamesdeanbarrett@hotmail.com;' ]
RR:
  auto_email: 'NO'
  delete_on_send: 'YES'
  email_recipients: [ 'jamesdeanbarrett@gmail.com; jamesdeanbarrett@hotmail.com;' ]
FWT:
  auto_email: 'NO'
  delete_on_send: 'NO'
  email_recipients: [ '' ]
