email_addresses:
  EH: ["email@com; email@com;"]
  RR: ["email@com; email@com;"]
  FWT: ["email@com; email@com;"]
  KB: ["email@com; email@com;"]
actions:
  auto_email_KB: "YES"
  auto_email_RR: "YES"
  auto_email_FWT: "No"
  auto_email_EH: "YES"
  auto_delete_on_send: "YES"


