email_addresses:
  EH: ["1@hotmail.com","2@gmail.com"]
  RR: ""
  FWT: ""
  KB: ""
actions:
  auto_email_KB: "YES"
  auto_email_RR: "YES"
  auto_email_FWT: "No"
  auto_email_EH: "YES"
  auto_delete_on_send: "YES"
